let sessionId=null, playerName='', score=0, step=1;
const $=id=>document.getElementById(id);
const show=id=>document.querySelectorAll('.screen').forEach(s=>s.id===id?s.classList.add('active'):s.classList.remove('active'));
async function api(url,body){try{await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch(e){console.warn(e)}}
async function startJourney(){
  playerName=($('name').value||'Seseorang').trim();
  const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:playerName})});
  const d=await r.json(); sessionId=d.id;
  await api('/api/event',{sessionId,type:'started',payload:{name:playerName}});
  step=1; score=0; show('game'); renderStep();
}
function setProgress(){ $('progressBar').style.width=(step/5*100)+'%'; $('stepLabel').textContent=`${step}/5`; }
function renderStep(){
  setProgress();
  const box=$('gameContent');
  if(step===1){box.innerHTML=`<div class="game-card"><p class="eyebrow">LEVEL 01 · FIRST IMPRESSION</p><h2 class="prompt">Seberapa kenal kamu sama<br><span style="color:var(--pink)">${playerName}</span>?</h2><p class="muted">Pilih jawaban yang paling terasa “kamu banget”. Ini bukan tes sekolah. Ini tes apakah kamu diam-diam merhatiin. 👀</p><div class="choices"><button class="choice" onclick="answer(10,'a')"><strong>Aku nggak yakin, tapi aku penasaran.</strong><small>Jujur adalah awal yang bagus.</small></button><button class="choice" onclick="answer(15,'b')"><strong>Aku lumayan hafal.</strong><small>Berarti ada yang kamu perhatiin.</small></button><button class="choice" onclick="answer(20,'c')"><strong>Kasih pertanyaan yang susah.</strong><small>Oke. Tantangan diterima.</small></button></div></div>`}
  if(step===2){box.innerHTML=`<div class="game-card"><p class="eyebrow">LEVEL 02 · HEART METER</p><h2 class="prompt">Ukur rasa kamu.</h2><p class="muted">Geser sampai angka yang menurutmu paling jujur. Nggak perlu pura-pura cool.</p><input id="heart" type="range" min="0" max="100" value="50" oninput="updateHeart(this.value)" style="width:100%;accent-color:#ff6ca7;margin-top:25px"><div class="heart-meter"><span id="heartFill" style="width:50%"></span></div><div class="score-line"><span>“biasa aja”</span><b id="heartValue">50%</b><span>“bahaya nih”</span></div><button class="primary" style="margin-top:28px" onclick="finishHeart()">Aku jujur kok →</button></div>`}
  if(step===3){box.innerHTML=`<div class="game-card"><p class="eyebrow">LEVEL 03 · EFFORT CHECK</p><h2 class="prompt">Mau buka satu pintu lagi?</h2><p class="muted">Ada 3 langkah kecil. Kamu nggak harus sempurna. Yang dilihat cuma: kamu mau sampai selesai atau nggak.</p><div class="choices"><button class="choice" onclick="effort('tap')"><strong>❤️ Tahan tombol ini 3 detik</strong><small>Karena rasa kadang butuh sedikit kesabaran.</small></button><button class="choice" onclick="effort('phrase')"><strong>💌 Tulis 3 kata untuk orang ini</strong><small>Yang pertama muncul di kepala.</small></button><button class="choice" onclick="effort('secret')"><strong>🔐 Cari kata rahasia</strong><small>Petunjuk: “hal yang terasa kalau kita dekat”.</small></button></div><div id="effortStatus" class="mini-note">0 / 3 pintu terbuka.</div></div>`}
  if(step===4){box.innerHTML=`<div class="game-card"><p class="eyebrow">LEVEL 04 · THE LITTLE THINGS</p><h2 class="prompt">Pilih satu.</h2><p class="muted">Bayangin kalian punya satu sore kosong. Mana yang paling kamu pilih?</p><div class="choices"><button class="choice" onclick="answer(15,'coffee')"><strong>☕ Ngobrol panjang sambil cari tempat nyaman.</strong><small>Nggak perlu ke mana-mana.</small></button><button class="choice" onclick="answer(15,'walk')"><strong>🌙 Jalan malam tanpa tujuan.</strong><small>Yang penting ada cerita.</small></button><button class="choice" onclick="answer(15,'movie')"><strong>🎬 Nonton, lalu debat filmnya.</strong><small>Setengah film, setengah flirting.</small></button></div></div>`}
  if(step===5){box.innerHTML=`<div class="game-card"><p class="eyebrow">LEVEL 05 · ONE LAST THING</p><h2 class="prompt">Kamu sudah sejauh ini.</h2><p class="muted">Sekarang buka pesan terakhir. Nggak ada tombol “skip”.</p><div class="secret"><b>Pesan terenkripsi</b><div style="font-size:28px;letter-spacing:.15em;margin:14px 0">♡ A K U ♡ K A M U ♡</div><span style="color:#ae9ca9">Klik buka untuk lanjut ke pertanyaan terakhir.</span></div><button class="primary" style="margin-top:20px" onclick="openResult()">Buka pesan →</button></div>`}
}
function answer(points,choice){score+=points;api('/api/event',{sessionId,type:'choice',payload:{step,choice,points}});step++;renderStep()}
function updateHeart(v){$('heartValue').textContent=v+'%';$('heartFill').style.width=v+'%'}
function finishHeart(){const v=Number($('heart').value);score+=Math.round(v/5);api('/api/event',{sessionId,type:'heart',payload:{value:v}});step=3;renderStep()}
let efforts=new Set(); let holdTimer;
function effort(kind){
 if(kind==='tap'){ if(efforts.has(kind))return; const btn=event.currentTarget; btn.textContent='❤️ Tahan...'; let n=0; holdTimer=setInterval(()=>{n+=100;if(n>=3000){clearInterval(holdTimer);efforts.add(kind);btn.textContent='✅ Berhasil';refreshEffort()}},100); window.addEventListener('pointerup',()=>clearInterval(holdTimer),{once:true}); }
 if(kind==='phrase'){const text=prompt('Tulis 3 kata yang menggambarkan dia:'); if(text&&text.trim().split(/\s+/).length>=3){efforts.add(kind);api('/api/event',{sessionId,type:'effort_phrase',payload:{text:text.slice(0,120)}});event.currentTarget.textContent='✅ Diterima';refreshEffort()}}
 if(kind==='secret'){const ans=prompt('Masukkan kata rahasia:'); if((ans||'').toLowerCase().includes('nyaman')){efforts.add(kind);api('/api/event',{sessionId,type:'effort_secret',payload:{success:true}});event.currentTarget.textContent='✅ Kuncinya ketemu';refreshEffort()}else{api('/api/event',{sessionId,type:'effort_secret',payload:{success:false}});alert('Belum. Petunjuknya: satu kata yang biasanya bikin hati tenang.')}}
}
function refreshEffort(){ $('effortStatus').textContent=`${efforts.size} / 3 pintu terbuka.`; if(efforts.size===3){score+=25;api('/api/event',{sessionId,type:'score',payload:{score}});setTimeout(()=>{step=4;renderStep()},650)}}
function openResult(){api('/api/event',{sessionId,type:'opened_final',payload:{score}}); $('resultTitle').textContent=`${playerName}, aku mau tanya sesuatu.`;$('resultText').innerHTML=`Aku sengaja bikin kamu sampai sejauh ini karena aku nggak mau pertanyaannya terasa biasa.<br><br><strong style="color:white;font-size:22px">Maukah kamu jadi pacarku?</strong>`;$('answerButtons').innerHTML=`<button class="primary" onclick="finish('IYA ❤️')">IYA. ❤️</button><button class="ghost" onclick="finish('Aku butuh waktu')">Aku butuh waktu</button>`;show('result')}
async function finish(answer){await api('/api/event',{sessionId,type:'completed',payload:{answer,score}});$('answerButtons').innerHTML=`<div style="padding:18px;border-radius:18px;background:#ffffff08;border:1px solid var(--line)"><b>Jawabanmu sudah sampai.</b><br><span style="color:var(--muted);font-size:13px">Terima kasih sudah menyelesaikan semuanya, ${playerName}. ♡</span></div>`;}
async function loadHistory(){const key=$('adminKey').value;const r=await fetch('/api/admin/history',{headers:{'x-admin-key':key}});if(!r.ok){alert('Admin key salah.');return}const d=await r.json();$('adminLogin').style.display='none';const map={};d.events.forEach(e=>(map[e.session_id]??=[]).push(e));$('historyList').innerHTML=d.sessions.map(s=>{const ev=(map[s.id]||[]).map(e=>`<div class="event"><b>${e.type}</b> · ${new Date(e.created_at).toLocaleString('id-ID')} ${Object.keys(e.payload||{}).length?`— ${escapeHtml(JSON.stringify(e.payload))}`:''}</div>`).join('');return `<div class="history-item"><div class="history-top"><div><b>${escapeHtml(s.name)}</b><div style="color:#8e7b88;font-size:12px;margin-top:5px">Mulai ${new Date(s.started_at).toLocaleString('id-ID')}</div></div><span class="badge">${s.completed_at?'SELESAI':'BERJALAN'} · ${s.score||0} poin</span></div>${s.final_answer?`<div style="margin-top:10px;color:var(--pink)">Jawaban: ${escapeHtml(s.final_answer)}</div>`:''}<div class="timeline">${ev||'<div class="event">Belum ada event.</div>'}</div></div>`}).join('')||'<p class="muted">Belum ada yang bermain.</p>'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if(location.hash==='#admin')show('admin');
